language: julia
os:
  - linux
julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly

branches:
  only:
    - master
    - /release-.*/

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

before_install:
  # download and install Wolfram Engine
  - wget -O WolframEngine.sh https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
  - printf "\n\n" | sudo bash WolframEngine.sh
  # information
  - WolframKernel -version
  - WolframKernel -machineid
  # activate
  - printf '\n1001-1010-456789\n8630-177-116:::20210630\n' | WolframKernel
