name: CI
on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
jobs:
  Linux:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    steps:
      - uses: actions/checkout@v2
      - run: WolframKernel -entitlement ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }} -pwfile '!cloudlm.wolfram.com' -noprompt -run 'WriteString[$Output,$InstallationDirectory];Exit[]'
      - run: WolframKernel -noprompt -run 'WriteString[$Output,$InstallationDirectory];Exit[]'
        env:
          WOLFRAMINIT:  -entitlement ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }} -pwfile !cloudlm.wolfram.com
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
          arch: x64 
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
